-- ═══════════════════════════════════════════════════════════════════
-- 書き込みの複製（2026-09-14 追加）
--
-- Vercel は同じミミックを何インスタンスも動かし、それぞれが独立した
-- インメモリ SQLite を抱える。片方で書いた結果を、もう片方に届ける必要がある。
--
-- ■ write_log をそのまま複製ログには使えない
--
-- あれは「意図の記録」であって「効果の記録」ではない。
--   ・採番の値が載っていない（db/write.mjs:252-258。after は cells だけ）
--   ・link の変更が載っていない（関連を張る が書き換えるが辺が残らない）
--   ・再計算の結果が載っていない（c.再計算 は COMMIT の外で UPDATE row SET calc を打つ）
--   ・再生が冪等でない（作る/更新/消す の再実行になると 検証() が走る）
--   ・行IDが再生側で変わる（"rec"+乱英数()）
--
-- ■ だから「やった結果」を持つ
--
-- 書き込みが終わった後の**行の最終形**をそのまま載せる。
-- 再生側は UPSERT / DELETE として当てるだけで、検証も採番も乱数も走らない。
-- 冪等で、seq 順なら決定的。**db/write.mjs は一行も変えない。**
-- ═══════════════════════════════════════════════════════════════════

create table if not exists effect (
  seq      bigint generated by default as identity primary key,
  at       text   not null,        -- ISO8601。write_log.at と同じ形
  who      text   not null,        -- どのインスタンスが書いたか（診断用）
  note     text,                   -- 出どころ（"画面 pag…/pel…" など）
  rows     text   not null,        -- JSON [{id,tbl,cells,calc,snap,implied,src,loaded} | {id,消す:true}]
  links    text   not null,        -- JSON {触った:[行ID…], 辺:[{src_row,fld,dst_row,ord}…]}
  counters text   not null,        -- JSON [{fld,next}…]
  logs     text   not null         -- JSON [write_log の新しい行…]
);

create index if not exists effect_seq on effect (seq);

-- ─────────── 書き込みを世界で 1 本ずつにする鍵 ───────────
--
-- pg_advisory_lock の鍵。採番（db/write.mjs:247 の 採る()）はインメモリの counter を
-- 読んで書くので、2 インスタンスが同時に走ると**同じ番号を配る**。
-- 書き込みの間だけ世界で 1 本にすれば、db/write.mjs を触らずに直る。
--
--   select pg_advisory_lock(8787001);   … 取る
--   select pg_advisory_unlock(8787001); … 返す
